"""Initial revision

Revision ID: 858da237f572
Revises: 
Create Date: 2026-03-03 16:19:37.621449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '858da237f572'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('surname', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telegram_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('categories',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('FOOD', 'TRANSPORT', 'ENTERTAINMENT', 'HEALTH', 'SHOPPING', 'UTILITIES',
                              'COMMUNICATION', 'CREDITS', 'EDUCATION', 'GIFTS', 'TRAVEL', 'CLOTHES', 'CAFE',
                              'SPORT', 'TAXES', 'REPAIRS', 'OTHER', name='expensecategory', create_type=False), nullable=False),
    sa.Column('monthly_budget', sa.Float(), nullable=True),
    sa.Column('currency', sa.Enum('RUB', 'USD', name='currency', create_type=False), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='unique_category_per_user')
    )
    op.create_table('budgets',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.Enum('DAY', 'WEEK', 'MONTH', 'YEAR', name='reportperiod', create_type=False), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.Enum('RUB', 'USD', name='currency', create_type=False), nullable=False),
    sa.Column('notify_at', sa.Integer(), nullable=False),
    sa.Column('last_notification_sent', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'category_id', 'period_start', name='unique_budget_per_period')
    )
    op.create_table('expenses',
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('expense_date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('BUDGET_EXCEEDED', 'MONTHLY_LIMIT', 'DAILY_LIMIT',
                              'DAILY_REPORT', 'WEEKLY_REPORT', 'MONTHLY_REPORT', 'REMINDER',
                              'REGULAR_EXPENSE', 'WELCOME', 'HELP', 'ERROR', 'INFO',
                              name='notificationtype', create_type=False), nullable=False),
    sa.Column('priority', sa.Enum('CRITICAL', 'HIGH', 'LOW', name='notificationpriority',
                                  create_type=False), nullable=False),
    sa.Column('category', sa.Enum('BUDGET', 'REPORTS', 'REMINDERS', 'SYSTEM',
                                  name='notificationcategory', create_type=False), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_delivered', sa.Boolean(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('expense_id', sa.Integer(), nullable=True),
    sa.Column('budget_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    op.drop_table('expenses')
    op.drop_table('budgets')
    op.drop_table('categories')
    op.drop_table('users')

    # Удаление типов ENUM
    # op.execute('DROP TYPE IF EXISTS expensecategory')
    # op.execute('DROP TYPE IF EXISTS currency')
    # op.execute('DROP TYPE IF EXISTS reportperiod')
    # op.execute('DROP TYPE IF EXISTS notificationtype')
    # op.execute('DROP TYPE IF EXISTS notificationcategory')
    # ### end Alembic commands ###
